:bug: Don't reuse DocumentBuilder, because it is not thread safe
org.xml.sax.SAXException: FWK005 parse may not be called while parsing.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:271)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at net.mm2d.upnp.util.XmlUtils.newDocument(XmlUtils.kt:67)
	at net.mm2d.upnp.internal.parser.DeviceParser.parseDescription$mmupnp(DeviceParser.kt:70)
	at net.mm2d.upnp.internal.parser.DeviceParser.loadDescription(DeviceParser.kt:53)
	at net.mm2d.upnp.internal.impl.ControlPointImpl.loadDevice(ControlPointImpl.kt:152)
	at net.mm2d.upnp.internal.impl.ControlPointImpl.access$loadDevice(ControlPointImpl.kt:35)
	at net.mm2d.upnp.internal.impl.ControlPointImpl$loadDevice$1.invoke(ControlPointImpl.kt:143)
	at net.mm2d.upnp.internal.impl.ControlPointImpl$loadDevice$1.invoke(ControlPointImpl.kt:35)
	at net.mm2d.upnp.internal.thread.TaskExecutors$io$1.run(TaskExecutors.kt:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)